spring.application.name=financeinfo
server.port=${SERVER_PORT:8000}

spring.datasource.url=${DB_URL:jdbc:mysql://mysql:3306/financeinformationdb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Juan24680*}

spring.jpa.show-sql=true

spring.mvc.log-request-details=true
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
