# SPRINGBOOT BACKENDS

FROM eclipse-temurin:21

WORKDIR /opt/app

COPY financeinfo-0.0.1-SNAPSHOT.jar financeinfo-0.0.1-SNAPSHOT.jar

EXPOSE 8000

ENTRYPOINT ["java", "-jar", "financeinfo-0.0.1-SNAPSHOT.jar"]